server:
  port: 1999

dubbo:
  application:
    name: dubbo-consumer
  registry:
    protocol: nacos
    address: 192.168.73.133:8848

spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true